// <auto-generated />
using System;
using Kwetter.Services.KweetService.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kwetter.Services.KweetService.Infrastructure.Migrations
{
    [DbContext(typeof(KweetDbContext))]
    partial class KweetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Kwetter.Services.KweetService.Domain.AggregatesModel.KweetAggregate.KweetAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Kweets");
                });

            modelBuilder.Entity("Kwetter.Services.KweetService.Domain.AggregatesModel.KweetAggregate.KweetAggregate", b =>
                {
                    b.OwnsMany("Kwetter.Services.KweetService.Domain.AggregatesModel.KweetAggregate.KweetLike", "Likes", b1 =>
                        {
                            b1.Property<Guid>("KweetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("KweetAggregateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("LikedDateTime")
                                .HasColumnType("datetime2");

                            b1.HasKey("KweetId", "UserId");

                            b1.HasIndex("KweetAggregateId");

                            b1.ToTable("KweetLike");

                            b1.WithOwner()
                                .HasForeignKey("KweetAggregateId");
                        });

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
