apiVersion: v1
kind: Service
metadata:
  name: eventstore
  namespace: kwetter
  labels:
    app: eventstore
spec:
  ports:
  - port: 2113
    targetPort: 2113
    name: eventstore-web
  - port: 1113
    targetPort: 1113
    name: eventstore-tcp
  - port: 2112
    targetPort: 2112
    name: gossip
  selector:
    app: eventstore
  type: ClusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventstore
  namespace: kwetter
spec:
  serviceName: eventstore
  replicas: 3
  selector:
    matchLabels:
      app: eventstore
  template:
    metadata:
      labels:
        app: eventstore
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - eventstore
              topologyKey: kubernetes.io/hostname
      containers:
      - name: eventstore
        image: eventstore/eventstore:20.10.2-bionic
        ports: 
        - containerPort: 1112
          name: eventstore-int-tcp
        - containerPort: 1113
          name: eventstore-ext-tcp
        - containerPort: 2113
          name: eventstore-web
        - containerPort: 2114
          name: gossip
        env:
        - name: EVENTSTORE_INT_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EVENTSTORE_EXT_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EVENTSTORE_CLUSTER_SIZE
          value: "3"
        - name: EVENTSTORE_DISCOVER_VIA_DNS
          value: "true"
        - name: EVENTSTORE_CLUSTER_DNS
          value: "eventstore.kwetter.svc.cluster.local"
        - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
          value: "true"
        - name: EVENTSTORE_INSECURE
          value: "true"
        - name: EVENTSTORE_INT_TCP_PORT
          value: "1112"
        - name: EVENTSTORE_EXT_TCP_PORT
          value: "1113"
        - name: EVENTSTORE_INT_HTTP_PORT
          value: "2114"
        - name: EVENTSTORE_EXT_HTTP_PORT
          value: "2113"
        - name: EVENTSTORE_INT_HTTP_PREFIXES
          value: "http://*:2114/"
        - name: EVENTSTORE_EXT_HTTP_PREFIXES
          value: "http://*:2113/"
        volumeMounts:
        - name: eventstore-data
          mountPath: /var/lib/eventstore
        livenessProbe:
          httpGet:
            path: /
            port: 2113
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 2113
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: eventstore-data
      namespace: kwetter
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 200Mi