apiVersion: v1
kind: Service
metadata:
  name: eventstore-cluster
  namespace: kwetter
  labels:
    app: eventstore-cluster
spec:
  clusterIP: None
  ports:
  - port: 2113
    targetPort: 2113
    name: eventstore-web
  - port: 1113
    targetPort: 1113
    name: eventstore-tcp
  - port: 2112
    targetPort: 2112
    name: gossip
  selector:
    app: eventstore-cluster
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventstore-cluster
  namespace: kwetter
spec:
  serviceName: eventstore-cluster
  replicas: 3
  selector:
    matchLabels:
      app: eventstore-cluster 
  template:
    metadata:
      labels:
        app: eventstore-cluster 
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - eventstore-cluster
              topologyKey: kubernetes.io/hostname
      containers:
      - name: eventstore
        image: eventstore/eventstore:20.10.2-bionic
        ports: 
        - containerPort: 2113
          name: eventstore-web
        - containerPort: 1113
          name: eventstore-tcp
        - containerPort: 2112
          name: gossip
        env:
        - name: EVENTSTORE_CLUSTER_SIZE
          value: "3"
        - name: EVENTSTORE_DISCOVER_VIA_DNS
          value: "true"
        - name: EVENTSTORE_CLUSTER_DNS
          value: "eventstore-cluster"
        - name: EVENTSTORE_EXT_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: EVENTSTORE_ENABLE_EXTERNAL_TCP
          value: "true"
        - name: EVENTSTORE_INSECURE
          value: "true"
        volumeMounts:
        - name: eventstore-cluster-data
          mountPath: /var/lib/eventstore
        livenessProbe:
          httpGet:
            path: /
            port: 2113
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 2113
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: eventstore-cluster-data
      namespace: kwetter
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 200Mi