apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eventstore-data-volume-claim
  namespace: kwetter
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: eventstore-data-volume
  namespace: kwetter
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/data/eventstore/
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: eventstore-data-volume-claim
    namespace: kwetter
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kmaster
